### ISSUE TITLE
Autobuild/push to docker hub not working properly?

### ISSUE THREAD

**Issue by andskli** [blacklabelops/jobber-cron#11]
Not sure how things are set up, but I'm assuming that blacklabelops/jobber-cron#10 should've triggered a build + push of `jobber:cloud` as well, however, looking at https://hub.docker.com/r/blacklabelops/jobber/tags/ it seems like that specific tag hasn't been updated recently.

**Comment by blacklabelops** [comment]
That's right. There is a problem building images with the gcloud-cli. 

The Dockerfile instruction `gcloud --quiet components update alpha beta app-engine-java app-engine-python kubectl bq core gsutil gcloud` fails since 14th February.

I deactivated the build until I can resolve it.

**Comment by blacklabelops** [comment]
Looks like there is a timeout when installing `app-engine-java`. I will remove that dependency this evening. Will make the image 120MB smaller, hope you do not need it.

**Comment by andskli** [comment]
I really don't know what impact that might give. The image build works on my machine<TM>. Temporary build error?

**Comment by blacklabelops** [comment]
Still investigating. Work on my machine, does not work on build host. Maybe because of many parallel builds and downloads.

**Comment by blacklabelops** [comment]
Daily build fixed! All tags are up to date. I do not think anybody will miss the cli commands to deploy java apps on the google apps engine.

**Comment by andskli** [comment]
👍
