### ISSUE TITLE
Problem Env Variable Containing ":"

### ISSUE THREAD

**Issue by blacklabelops** [blacklabelops/jobber-cron#13]
Docker-Compose uses some environment variable `container:affinity`. This hinders the execution of scripts cause the pre-script exporting all env variables cannot run with one of these.

**Comment by haphan** [comment]
`sed -i.bak '/:/d' ${environmentfile}` mistakenly removes environment variables in form of an url, e.g. `https://google.com`

**Comment by blacklabelops** [comment]
I see, I will provide a bugfix shortly.
