### ISSUE TITLE
support notifyProgram

### ISSUE THREAD

**Issue by colthreepv** [blacklabelops/jobber-cron#15]
Hi, it would be useful to setup `notifyProgram` via ENV variables

using the default `sendmail` is particularly useless with docker

**Comment by blacklabelops** [comment]
notifyProgram is supported in which jobber version?

**Comment by colthreepv** [comment]
[it should be a new 1.2 functionality](http://dshearer.github.io/jobber/doc/v1.2/), it's not written in the [release notes](https://github.com/dshearer/jobber/releases)

I am not sure if it's a "stealth change" or it always been there, just not documented

**Comment by colthreepv** [comment]
**update:** I am producing a PR for this functionality, sounds acceptable to include [jq](https://stedolan.github.io/jq/) in the building process? It's a JSON parser, the notifyProgram payload is a JSON

In such way a user can write a script using most common bash operations without subclassing to another Dockerfile just to add a JSON parser

PS: maybe also curl is very useful... but... I am not sure

**Comment by blacklabelops** [comment]
If you need any tool, you can add it simply to blacklabelops/jobber:tools. The tools image is ment to be the swiss knife of cron.

**Comment by colthreepv** [comment]
Yes, I added `jq` on jobber-tools, I hope it's fine for you

**Comment by blacklabelops** [comment]
Absolutely. It's been ment for that.

**Comment by blacklabelops** [comment]
Finished.
