### ISSUE TITLE
Best way to add an apt-get dependency?

### ISSUE THREAD

**Issue by binary64** [blacklabelops/jobber-cron#19]
Hi I'm trying to execute `php` in another container. Which route would you recommend:-

1. Install `docker` into jobber-cron, and volume map the .sock then run docker exec..
2. Map jobber-cron to /usr/bin then run /host/usr/bin/docker ..?
3. Fork your repo and build my own image
4. Ask you to allow a new env var to specify needed apt-get packages eg APTGET=docker
5. Or any other way?

Many thanks

**Comment by blacklabelops** [comment]
The easiest way is to send commands via `docker exec ...` to the other container. I would recommend that way.

I would never go over host binaries with Docker. I do not apply isolated containers and then rely on a host infrastructure binaries/folders/installations. That's the "old world".

If you need your own packages then the correct way is to extend this image.

- Use this image as a base image.
- Install your programs via apk.
- Use you extended image.

This image is based on Alpine Linux. There is no way to install anything on Alpine with the Ubuntu Package Manager APT. You will have to make your own image based on Ubuntu.

**Comment by binary64** [comment]
Many thanks, you've been very helpful!
