### ISSUE TITLE
Clarification on "clobbering"

### ISSUE THREAD

**Issue by binary64** [blacklabelops/jobber-cron#20]
I have a question, if I execute a task every 1 second, but sometimes the task sometimes takes 5 seconds.. what happens? Can we have an option to either Serialize -or- Parallel?

**Comment by blacklabelops** [comment]
Jobber triggers jobs dumbly. So there is a chance your jobs get executed in parallel.

Please state your proposal to the Jobber repository, because this is just a Docker Image for Jobber:

https://github.com/dshearer/jobber

**Comment by blacklabelops** [comment]
Blacklabelops/cronium can do this: https://github.com/blacklabelops/cronium
