### ISSUE TITLE
Time Interval Randomized Seed

### ISSUE THREAD

**Issue by binary64** [blacklabelops/jobber-cron#21]
Hi I plan on having many instances of jobber-cron running, all with the same timing config. This leads to an issue for my hourly cron where multiple containers will all work at the same millisecond. I would like to specify something like this for the interval:

`? * * * * *`

where the `?` means "Select a random value within the range (0-59 in this case), and stick with it!" so for example on init it would choose 35 let's say.. so every *:*:35 it will now execute.

For midnight cron, I would want it random between midnight and 1am I think.. so something like `? ? 0` could work so for example it might execute every 00:32:11am

**Comment by blacklabelops** [comment]
Please check the jobber documentation:

http://dshearer.github.io/jobber/doc/v1.2/#defining-jobs
