### ISSUE TITLE
Docker Version

### ISSUE THREAD

**Issue by davidwindell** [blacklabelops/jobber-cron#25]
Would you consider releasing an updated version with a later version of the Docker client?

We want to use `docker system prune` in our jobs but it is only available in API 1.25+

**Comment by blacklabelops** [comment]
Sure, when I figured out the new Docker installation routine.

**Comment by davidwindell** [comment]
We just do it like this https://github.com/outeredge/edge-docker-che-base/blob/master/Dockerfile if that helps

**Comment by blacklabelops** [comment]
Thank you but I prefer a curl-based solution. It's already provided by one of my base images.

**Comment by blacklabelops** [comment]
New version of blacklabelops/jobber:docker released!

**Comment by blacklabelops** [comment]
New version of blacklabelops/jobber:cloud released!

**Comment by davidwindell** [comment]
Thanks, that works great! :+1:
