### ISSUE TITLE
Base jobber image doesn't build without adding rsync

### ISSUE THREAD

**Issue by jukie** [blacklabelops/jobber-cron#28]
Get the below output when trying to build, I'll submit a pr.
`package github.com/dshearer/jobber: no Go files in /tmp/jobber/lib/src/github.com/dshearer/jobber
make: Entering directory '/tmp/jobber/lib/src/github.com/dshearer/jobber'
MAKE GOYACC
/bin/sh: rsync: not found
make: *** [mk/buildtools.mk:11: /tmp/jobber/lib/src/github.com/dshearer/jobber/buildtools/gen/bin/goyacc] Error 127
make: Leaving directory '/tmp/jobber/lib/src/github.com/dshearer/jobber'`

**Comment by blacklabelops** [comment]
Sorry, this repository is not supported anymore.
