### ISSUE TITLE
Error and then container restarts

### ISSUE THREAD

**Issue by cloudlady911** [blacklabelops/jobber-cron#5]
Trying to use Jobber:aws.  I get this error: 

`5/9/2016 7:20:12 PM/opt/cloud/environment-amazonws.sh: /usr/bin/aws: /usr/bin/python: bad interpreter: No such file or directory`  Then the container restarts.

**Comment by blacklabelops** [comment]
I have the same problem! I will fix it. Meanwhile, please use the image: blacklabelops/cron-cloud.

**Comment by blacklabelops** [comment]
Fixed the issue, new image will be pushed shortly on dockerhub.
