### ISSUE TITLE
Time Question

### ISSUE THREAD

**Issue by cloudlady911** [blacklabelops/jobber-cron#6]
Can I use all  the cron shortcuts, like @hourly?  If not, how would I write the Job_Time parameter if I want something to run hourly?

**Comment by blacklabelops** [comment]
Jobber has not full cron library and is limited to some simple expressions. If you want to run something hourly you will have to fix seconds and minutes, e.g.: "0 0 \* \* \* *"

Jobber's documentation on cron strings can be found here: http://dshearer.github.io/jobber/#time-strings
