### ISSUE TITLE
jobberd: command not found

### ISSUE THREAD

**Issue by rthrfrd** [blacklabelops/jobber-cron#7]
Can't tell if I'm just being stupid but whenever I try to run this container (e.g. Using README demo command):

``` sh
docker run -d --name jobber -e "JOB_NAME1=TestEcho" -e "JOB_COMMAND1=echo hello world" blacklabelops/jobber
```

Docker logs just yields:

``` sh
/opt/jobber/docker-entrypoint.sh: line 55: jobberd: command not found
```

I've tried overriding the entrypoint to take a look inside the container with it running and can't find jobber anywhere...

**Comment by blacklabelops** [comment]
Jobber installation routine changed meanwhile and still working on improved tests.
