### ISSUE TITLE
Environment variable name with non-alphanumeric character causes shell error

### ISSUE THREAD

**Issue by jessemortenson** [blacklabelops/jobber-cron#8]
Hello - cool image! I tried it out and ran into this issue, which prevented my task from running:

```
Running job "Spider" for user "root"...
Job "Spider" failed.
New status: Good.

Stdout:


Stderr:
-sh: export: line 3: DCNEW_SCRAPYD_1_ENV_affinity:container: bad variable name
```

Looking at the file /etc/profile.d/jobber.sh in the container shows this variable:

`export DCNEW_SCRAPYD_1_ENV_affinity:container='=8fe6d49e6ce66e5373326afb2f0d473e6fe44fe7bfff5a7e6829157882d5830a'`

It looks like the colon in the variable name [is not allowed](http://stackoverflow.com/a/2821183). You'd think that `sh export` would take care of that, but apparently not. It looks like your image pipelines environment variables into the job that is run, but is hitting an error with this variable name. That environment variable is added by docker-compose, I think.

My solution was to modify the image to install perl, and modify the code in docker-entrypoint.sh to the following:

``` bash
function pipeEnvironmentVariables() {
  local environmentfile="/etc/profile.d/jobber.sh"
  cat > ${environmentfile} <<_EOF_
  #!/bin/sh
_EOF_
  sh -c export | perl -ne 's/(?<=export )(.+)(?=\='\'')/$new = $1; $new =~ s\/[^[:alnum:]]\/_\/g; $new/eg; print;' >> ${environmentfile}
}
```

Hope that helps. I'm not a regex master, so there is probably a better solution than substitution regex nested inside of another substitution regex. I wanted to do it with sed but couldn't figure out a solution that would _only_ replace instances in the variable name (not the variable value) and also replace multiple instances (in case variable name has multiple non-alphanumeric characters). It's also not a perfect solution because scripts might be expecting those environment var names (with colons or whatever) and folks would get confused that they are being renamed. But don't immediately see a way around it.

**Comment by blacklabelops** [comment]
I had to upgrade docker-compose in order to solve this issue. The "affinity" env variable will be set by docker-compose when you recreate a container. Should not happen in the latest docker-compose release.
